name: run-checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run linting"
        run: pnpm lint

      - name: "Build the project"
        run: pnpm build

  test:
    name: Test
    needs: build-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Pull mongodb image"
        run: docker pull mongodb/mongodb-community-server:7.0.12-ubi8

      - name: "Run tests and collect coverage"
        run: pnpm test:coverage
